// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const countCategoriesByLedger = `-- name: CountCategoriesByLedger :one
SELECT COUNT(*)
FROM categories
WHERE ledger_id = ?
`

func (q *Queries) CountCategoriesByLedger(ctx context.Context, ledgerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByLedger, ledgerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChildCategories = `-- name: CountChildCategories :one
SELECT COUNT(*)
FROM categories
WHERE parent_id = ?
`

func (q *Queries) CountChildCategories(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildCategories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSourcesByLedger = `-- name: CountSourcesByLedger :one
SELECT COUNT(*)
FROM sources
WHERE ledger_id = ?
`

func (q *Queries) CountSourcesByLedger(ctx context.Context, ledgerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSourcesByLedger, ledgerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByCategory = `-- name: CountTransactionsByCategory :one
SELECT COUNT(*)
FROM transactions
WHERE category_id = ?
`

func (q *Queries) CountTransactionsByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByLedger = `-- name: CountTransactionsByLedger :one
SELECT COUNT(*)
FROM transactions
WHERE ledger_id = ?
`

func (q *Queries) CountTransactionsByLedger(ctx context.Context, ledgerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByLedger, ledgerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsBySource = `-- name: CountTransactionsBySource :one
SELECT COUNT(*)
FROM transactions
WHERE source_id = ?
`

func (q *Queries) CountTransactionsBySource(ctx context.Context, sourceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (ledger_id, name, parent_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, ledger_id, name, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	LedgerID  int64
	Name      string
	ParentID  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.LedgerID,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedger = `-- name: CreateLedger :one
INSERT INTO ledgers (name, comment, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, comment, created_at, updated_at
`

type CreateLedgerParams struct {
	Name      string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error) {
	row := q.db.QueryRowContext(ctx, createLedger,
		arg.Name,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (ledger_id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, ledger_id, name, created_at, updated_at
`

type CreateSourceParams struct {
	LedgerID  int64
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.LedgerID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (ledger_id, type, source_id, category_id, currency, amount, time, comment, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, ledger_id, type, source_id, category_id, currency, amount, time, comment, created_at, updated_at
`

type CreateTransactionParams struct {
	LedgerID   int64
	Type       string
	SourceID   int64
	CategoryID int64
	Currency   string
	Amount     int64
	Time       int64
	Comment    string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.LedgerID,
		arg.Type,
		arg.SourceID,
		arg.CategoryID,
		arg.Currency,
		arg.Amount,
		arg.Time,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Type,
		&i.SourceID,
		&i.CategoryID,
		&i.Currency,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteLedger = `-- name: DeleteLedger :exec
DELETE FROM ledgers
WHERE id = ?
`

func (q *Queries) DeleteLedger(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLedger, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources
WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, ledger_id, name, parent_id, created_at, updated_at
FROM categories
WHERE id = ? AND ledger_id = ?
`

type GetCategoryParams struct {
	ID       int64
	LedgerID int64
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.ID, arg.LedgerID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedger = `-- name: GetLedger :one
SELECT id, name, comment, created_at, updated_at
FROM ledgers
WHERE id = ?
`

func (q *Queries) GetLedger(ctx context.Context, id int64) (Ledger, error) {
	row := q.db.QueryRowContext(ctx, getLedger, id)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, ledger_id, name, created_at, updated_at
FROM sources
WHERE id = ? AND ledger_id = ?
`

type GetSourceParams struct {
	ID       int64
	LedgerID int64
}

func (q *Queries) GetSource(ctx context.Context, arg GetSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, arg.ID, arg.LedgerID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, ledger_id, type, source_id, category_id, currency, amount, time, comment, created_at, updated_at
FROM transactions
WHERE id = ? AND ledger_id = ?
`

type GetTransactionParams struct {
	ID       int64
	LedgerID int64
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, arg.ID, arg.LedgerID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Type,
		&i.SourceID,
		&i.CategoryID,
		&i.Currency,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, ledger_id, name, parent_id, created_at, updated_at
FROM categories
WHERE ledger_id = ?
ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context, ledgerID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryDescendantIDs = `-- name: ListCategoryDescendantIDs :many
WITH RECURSIVE descendants(id) AS (
    SELECT c.id FROM categories c WHERE c.parent_id = ?1
    UNION ALL
    SELECT c.id FROM categories c
    JOIN descendants d ON c.parent_id = d.id
)
SELECT id FROM descendants
`

func (q *Queries) ListCategoryDescendantIDs(ctx context.Context, targetID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryDescendantIDs, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgers = `-- name: ListLedgers :many
SELECT id, name, comment, created_at, updated_at
FROM ledgers
ORDER BY id
`

func (q *Queries) ListLedgers(ctx context.Context) ([]Ledger, error) {
	rows, err := q.db.QueryContext(ctx, listLedgers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, ledger_id, name, created_at, updated_at
FROM sources
WHERE ledger_id = ?
ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context, ledgerID int64) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT id, ledger_id, type, source_id, category_id, currency, amount, time, comment, created_at, updated_at
FROM transactions
WHERE ledger_id = ?1
  AND (?2   IS NULL OR source_id = ?2)
  AND (?3 IS NULL OR category_id = ?3)
  AND (?4  IS NULL OR time >= ?4)
  AND (?5    IS NULL OR time <= ?5)
  AND (?6     IS NULL OR (LOWER(comment) LIKE '%' || LOWER(?6) || '%' ESCAPE '\'))
  AND (
    ?7 IS NULL
    OR time > ?7
    OR (time = ?7 AND id > ?8)
  )
ORDER BY time, id
LIMIT ?9
`

type SearchTransactionsParams struct {
	LedgerID   int64
	SourceID   interface{}
	CategoryID interface{}
	StartTime  interface{}
	EndTime    interface{}
	Keyword    interface{}
	AfterTime  interface{}
	AfterID    sql.NullInt64
	Limit      int64
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactions,
		arg.LedgerID,
		arg.SourceID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.Keyword,
		arg.AfterTime,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.Type,
			&i.SourceID,
			&i.CategoryID,
			&i.Currency,
			&i.Amount,
			&i.Time,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactionsDesc = `-- name: SearchTransactionsDesc :many
SELECT id, ledger_id, type, source_id, category_id, currency, amount, time, comment, created_at, updated_at
FROM transactions
WHERE ledger_id = ?1
  AND (?2   IS NULL OR source_id = ?2)
  AND (?3 IS NULL OR category_id = ?3)
  AND (?4  IS NULL OR time >= ?4)
  AND (?5    IS NULL OR time <= ?5)
  AND (?6     IS NULL OR (LOWER(comment) LIKE '%' || LOWER(?6) || '%' ESCAPE '\'))
  AND (
    ?7 IS NULL
    OR time < ?7
    OR (time = ?7 AND id < ?8)
  )
ORDER BY time DESC, id DESC
LIMIT ?9
`

type SearchTransactionsDescParams struct {
	LedgerID   int64
	SourceID   interface{}
	CategoryID interface{}
	StartTime  interface{}
	EndTime    interface{}
	Keyword    interface{}
	AfterTime  interface{}
	AfterID    sql.NullInt64
	Limit      int64
}

// Same filters as SearchTransactions, but ordered newest-first and with the
// keyset comparison flipped so next_cursor pages toward earlier transactions.
// Used by search_transactions when newest_first is set (see
// add-transaction-timeline-widget).
func (q *Queries) SearchTransactionsDesc(ctx context.Context, arg SearchTransactionsDescParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactionsDesc,
		arg.LedgerID,
		arg.SourceID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.Keyword,
		arg.AfterTime,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.Type,
			&i.SourceID,
			&i.CategoryID,
			&i.Currency,
			&i.Amount,
			&i.Time,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeTransactionsByCategory = `-- name: SummarizeTransactionsByCategory :many
SELECT
    t.category_id AS category_id,
    t.currency AS currency,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN -t.amount ELSE 0 END), 0) AS INTEGER) AS expense
FROM transactions t
WHERE t.ledger_id = ?1
  AND (?2 IS NULL OR t.time >= ?2)
  AND (?3   IS NULL OR t.time <= ?3)
GROUP BY t.category_id, t.currency
ORDER BY t.category_id, t.currency
`

type SummarizeTransactionsByCategoryParams struct {
	LedgerID  int64
	StartTime interface{}
	EndTime   interface{}
}

type SummarizeTransactionsByCategoryRow struct {
	CategoryID int64
	Currency   string
	Income     int64
	Expense    int64
}

// Aggregates income/expense totals grouped by category and currency, within
// one ledger, over an optional [start_time, end_time] window.
func (q *Queries) SummarizeTransactionsByCategory(ctx context.Context, arg SummarizeTransactionsByCategoryParams) ([]SummarizeTransactionsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeTransactionsByCategory, arg.LedgerID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeTransactionsByCategoryRow{}
	for rows.Next() {
		var i SummarizeTransactionsByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Currency,
			&i.Income,
			&i.Expense,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeTransactionsByCurrency = `-- name: SummarizeTransactionsByCurrency :many
SELECT
    t.currency AS currency,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN -t.amount ELSE 0 END), 0) AS INTEGER) AS expense
FROM transactions t
WHERE t.ledger_id = ?1
  AND (?2 IS NULL OR t.time >= ?2)
  AND (?3   IS NULL OR t.time <= ?3)
GROUP BY t.currency
ORDER BY t.currency
`

type SummarizeTransactionsByCurrencyParams struct {
	LedgerID  int64
	StartTime interface{}
	EndTime   interface{}
}

type SummarizeTransactionsByCurrencyRow struct {
	Currency string
	Income   int64
	Expense  int64
}

// Aggregates income/expense totals grouped by the transaction's own
// currency, within one ledger, over an optional [start_time, end_time]
// window. Used by get_financial_summary (internal/tools/analytics.go).
// expense amounts are stored negative, so SUM(-amount) turns them back into
// a positive total.
func (q *Queries) SummarizeTransactionsByCurrency(ctx context.Context, arg SummarizeTransactionsByCurrencyParams) ([]SummarizeTransactionsByCurrencyRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeTransactionsByCurrency, arg.LedgerID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeTransactionsByCurrencyRow{}
	for rows.Next() {
		var i SummarizeTransactionsByCurrencyRow
		if err := rows.Scan(&i.Currency, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeTransactionsBySource = `-- name: SummarizeTransactionsBySource :many
SELECT
    t.source_id AS source_id,
    t.currency AS currency,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN -t.amount ELSE 0 END), 0) AS INTEGER) AS expense
FROM transactions t
WHERE t.ledger_id = ?1
  AND (?2 IS NULL OR t.time >= ?2)
  AND (?3   IS NULL OR t.time <= ?3)
GROUP BY t.source_id, t.currency
ORDER BY t.source_id, t.currency
`

type SummarizeTransactionsBySourceParams struct {
	LedgerID  int64
	StartTime interface{}
	EndTime   interface{}
}

type SummarizeTransactionsBySourceRow struct {
	SourceID int64
	Currency string
	Income   int64
	Expense  int64
}

// Aggregates income/expense totals grouped by source and currency, within
// one ledger, over an optional [start_time, end_time] window.
func (q *Queries) SummarizeTransactionsBySource(ctx context.Context, arg SummarizeTransactionsBySourceParams) ([]SummarizeTransactionsBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeTransactionsBySource, arg.LedgerID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeTransactionsBySourceRow{}
	for rows.Next() {
		var i SummarizeTransactionsBySourceRow
		if err := rows.Scan(
			&i.SourceID,
			&i.Currency,
			&i.Income,
			&i.Expense,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionStats = `-- name: TransactionStats :one
SELECT
    COUNT(*) AS count,
    MIN(time) AS earliest_time,
    MAX(time) AS latest_time
FROM transactions
WHERE ledger_id = ?1
`

type TransactionStatsRow struct {
	Count        int64
	EarliestTime interface{}
	LatestTime   interface{}
}

// Total count and the earliest/latest transaction time in one ledger. Used by
// open_transaction_timeline for its degradation summary. count is 0 and the
// times are NULL when the ledger has no transactions.
func (q *Queries) TransactionStats(ctx context.Context, ledgerID int64) (TransactionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, transactionStats, ledgerID)
	var i TransactionStatsRow
	err := row.Scan(&i.Count, &i.EarliestTime, &i.LatestTime)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = ?, parent_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, ledger_id, name, parent_id, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name      string
	ParentID  int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.ParentID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLedger = `-- name: UpdateLedger :one
UPDATE ledgers
SET name = ?, comment = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, comment, created_at, updated_at
`

type UpdateLedgerParams struct {
	Name      string
	Comment   string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateLedger(ctx context.Context, arg UpdateLedgerParams) (Ledger, error) {
	row := q.db.QueryRowContext(ctx, updateLedger,
		arg.Name,
		arg.Comment,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET name = ?, updated_at = ?
WHERE id = ?
RETURNING id, ledger_id, name, created_at, updated_at
`

type UpdateSourceParams struct {
	Name      string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, updateSource, arg.Name, arg.UpdatedAt, arg.ID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET type = ?, source_id = ?, category_id = ?, currency = ?, amount = ?, time = ?, comment = ?, updated_at = ?
WHERE id = ?
RETURNING id, ledger_id, type, source_id, category_id, currency, amount, time, comment, created_at, updated_at
`

type UpdateTransactionParams struct {
	Type       string
	SourceID   int64
	CategoryID int64
	Currency   string
	Amount     int64
	Time       int64
	Comment    string
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.Type,
		arg.SourceID,
		arg.CategoryID,
		arg.Currency,
		arg.Amount,
		arg.Time,
		arg.Comment,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Type,
		&i.SourceID,
		&i.CategoryID,
		&i.Currency,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
