// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Category struct {
	ID        int64
	LedgerID  int64
	Name      string
	ParentID  int64
	CreatedAt int64
	UpdatedAt int64
}

type Ledger struct {
	ID        int64
	Name      string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
}

type Source struct {
	ID        int64
	LedgerID  int64
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type Transaction struct {
	ID         int64
	LedgerID   int64
	Type       string
	SourceID   int64
	CategoryID int64
	Currency   string
	Amount     int64
	Time       int64
	Comment    string
	CreatedAt  int64
	UpdatedAt  int64
}
