// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
}

type Category struct {
	ID        int64
	Name      string
	ParentID  int64
	CreatedAt int64
	UpdatedAt int64
}

type Transaction struct {
	ID         int64
	Type       string
	AccountID  int64
	CategoryID sql.NullInt64
	Amount     int64
	Time       int64
	Comment    string
	CreatedAt  int64
}
