// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type, currency, comment, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, type, currency, comment, created_at, updated_at
`

type CreateAccountParams struct {
	Name      string
	Type      string
	Currency  string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, type, parent_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, type, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	Name      string
	Type      string
	ParentID  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Type,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (type, account_id, category_id, amount, time, comment, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, type, account_id, category_id, amount, time, comment, created_at
`

type CreateTransactionParams struct {
	Type       string
	AccountID  int64
	CategoryID sql.NullInt64
	Amount     int64
	Time       int64
	Comment    string
	CreatedAt  int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Time,
		arg.Comment,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, type, currency, comment, created_at, updated_at
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) AS balance
FROM transactions
WHERE account_id = ?
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, type, parent_id, created_at, updated_at
FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, account_id, category_id, amount, time, comment, created_at
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
    a.id, a.name, a.type, a.currency, a.comment, a.created_at, a.updated_at,
    CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id
GROUP BY a.id
ORDER BY a.id
`

type ListAccountsRow struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
	Balance   int64
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type, parent_id, created_at, updated_at
FROM categories
ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT id, type, account_id, category_id, amount, time, comment, created_at
FROM transactions
WHERE (?1  IS NULL OR account_id = ?1)
  AND (?2 IS NULL OR category_id = ?2)
  AND (?3  IS NULL OR time >= ?3)
  AND (?4    IS NULL OR time <= ?4)
ORDER BY time, id
`

type SearchTransactionsParams struct {
	AccountID  interface{}
	CategoryID interface{}
	StartTime  interface{}
	EndTime    interface{}
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactions,
		arg.AccountID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Time,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
