// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const countChildCategories = `-- name: CountChildCategories :one
SELECT COUNT(*)
FROM categories
WHERE parent_id = ?
`

func (q *Queries) CountChildCategories(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildCategories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByAccount = `-- name: CountTransactionsByAccount :one
SELECT COUNT(*)
FROM transactions
WHERE account_id = ?
`

func (q *Queries) CountTransactionsByAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByCategory = `-- name: CountTransactionsByCategory :one
SELECT COUNT(*)
FROM transactions
WHERE category_id = ?
`

func (q *Queries) CountTransactionsByCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type, currency, comment, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, type, currency, comment, created_at, updated_at
`

type CreateAccountParams struct {
	Name      string
	Type      string
	Currency  string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	Name      string
	ParentID  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (type, account_id, category_id, amount, time, comment, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, type, account_id, category_id, amount, time, comment, created_at, updated_at
`

type CreateTransactionParams struct {
	Type       string
	AccountID  int64
	CategoryID sql.NullInt64
	Amount     int64
	Time       int64
	Comment    string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Time,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, type, currency, comment, created_at, updated_at
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) AS balance
FROM transactions
WHERE account_id = ?
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, parent_id, created_at, updated_at
FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, account_id, category_id, amount, time, comment, created_at, updated_at
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
    a.id, a.name, a.type, a.currency, a.comment, a.created_at, a.updated_at,
    CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id
GROUP BY a.id
ORDER BY a.id
`

type ListAccountsRow struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	Comment   string
	CreatedAt int64
	UpdatedAt int64
	Balance   int64
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id, created_at, updated_at
FROM categories
ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryDescendantIDs = `-- name: ListCategoryDescendantIDs :many
WITH RECURSIVE descendants(id) AS (
    SELECT c.id FROM categories c WHERE c.parent_id = ?1
    UNION ALL
    SELECT c.id FROM categories c
    JOIN descendants d ON c.parent_id = d.id
)
SELECT id FROM descendants
`

func (q *Queries) ListCategoryDescendantIDs(ctx context.Context, targetID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryDescendantIDs, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT id, type, account_id, category_id, amount, time, comment, created_at, updated_at
FROM transactions
WHERE (?1  IS NULL OR account_id = ?1)
  AND (?2 IS NULL OR category_id = ?2)
  AND (?3  IS NULL OR time >= ?3)
  AND (?4    IS NULL OR time <= ?4)
  AND (
    ?5 IS NULL
    OR time > ?5
    OR (time = ?5 AND id > ?6)
  )
ORDER BY time, id
LIMIT ?7
`

type SearchTransactionsParams struct {
	AccountID  interface{}
	CategoryID interface{}
	StartTime  interface{}
	EndTime    interface{}
	AfterTime  interface{}
	AfterID    sql.NullInt64
	Limit      int64
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactions,
		arg.AccountID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.AfterTime,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Time,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeTransactionsByAccount = `-- name: SummarizeTransactionsByAccount :many
SELECT
    t.account_id AS account_id,
    a.currency AS currency,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN -t.amount ELSE 0 END), 0) AS INTEGER) AS expense
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.type IN ('income', 'expense')
  AND (?1 IS NULL OR t.time >= ?1)
  AND (?2   IS NULL OR t.time <= ?2)
GROUP BY t.account_id, a.currency
ORDER BY t.account_id, a.currency
`

type SummarizeTransactionsByAccountParams struct {
	StartTime interface{}
	EndTime   interface{}
}

type SummarizeTransactionsByAccountRow struct {
	AccountID int64
	Currency  string
	Income    int64
	Expense   int64
}

// Aggregates income/expense totals grouped by account, over an optional
// [start_time, end_time] window. adjustment transactions are
// excluded (see SummarizeTransactionsByCurrency for their total).
func (q *Queries) SummarizeTransactionsByAccount(ctx context.Context, arg SummarizeTransactionsByAccountParams) ([]SummarizeTransactionsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeTransactionsByAccount, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeTransactionsByAccountRow{}
	for rows.Next() {
		var i SummarizeTransactionsByAccountRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Currency,
			&i.Income,
			&i.Expense,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeTransactionsByCategory = `-- name: SummarizeTransactionsByCategory :many
SELECT
    t.category_id AS category_id,
    a.currency AS currency,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN -t.amount ELSE 0 END), 0) AS INTEGER) AS expense
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.type IN ('income', 'expense')
  AND (?1 IS NULL OR t.time >= ?1)
  AND (?2   IS NULL OR t.time <= ?2)
GROUP BY t.category_id, a.currency
ORDER BY t.category_id, a.currency
`

type SummarizeTransactionsByCategoryParams struct {
	StartTime interface{}
	EndTime   interface{}
}

type SummarizeTransactionsByCategoryRow struct {
	CategoryID sql.NullInt64
	Currency   string
	Income     int64
	Expense    int64
}

// Aggregates income/expense totals grouped by category and account
// currency, over an optional [start_time, end_time] window.
// adjustment transactions have no category and are excluded.
func (q *Queries) SummarizeTransactionsByCategory(ctx context.Context, arg SummarizeTransactionsByCategoryParams) ([]SummarizeTransactionsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeTransactionsByCategory, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeTransactionsByCategoryRow{}
	for rows.Next() {
		var i SummarizeTransactionsByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Currency,
			&i.Income,
			&i.Expense,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeTransactionsByCurrency = `-- name: SummarizeTransactionsByCurrency :many
SELECT
    a.currency AS currency,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN -t.amount ELSE 0 END), 0) AS INTEGER) AS expense,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'adjustment' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS adjustment
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE (?1 IS NULL OR t.time >= ?1)
  AND (?2   IS NULL OR t.time <= ?2)
GROUP BY a.currency
ORDER BY a.currency
`

type SummarizeTransactionsByCurrencyParams struct {
	StartTime interface{}
	EndTime   interface{}
}

type SummarizeTransactionsByCurrencyRow struct {
	Currency   string
	Income     int64
	Expense    int64
	Adjustment int64
}

// Aggregates income/expense/adjustment totals grouped by account
// currency, over an optional [start_time, end_time] window. Used by
// get_financial_summary (internal/tools/analytics.go). expense amounts are
// stored negative, so SUM(-amount) turns them back into a positive total;
// adjustment is reported here but excluded from income/expense by
// SummarizeTransactionsByCategory/ByAccount below.
func (q *Queries) SummarizeTransactionsByCurrency(ctx context.Context, arg SummarizeTransactionsByCurrencyParams) ([]SummarizeTransactionsByCurrencyRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizeTransactionsByCurrency, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeTransactionsByCurrencyRow{}
	for rows.Next() {
		var i SummarizeTransactionsByCurrencyRow
		if err := rows.Scan(
			&i.Currency,
			&i.Income,
			&i.Expense,
			&i.Adjustment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = ?, type = ?, comment = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, type, currency, comment, created_at, updated_at
`

type UpdateAccountParams struct {
	Name      string
	Type      string
	Comment   string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Comment,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = ?, parent_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, parent_id, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name      string
	ParentID  int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.ParentID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET type = ?, account_id = ?, category_id = ?, amount = ?, time = ?, comment = ?, updated_at = ?
WHERE id = ?
RETURNING id, type, account_id, category_id, amount, time, comment, created_at, updated_at
`

type UpdateTransactionParams struct {
	Type       string
	AccountID  int64
	CategoryID sql.NullInt64
	Amount     int64
	Time       int64
	Comment    string
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Time,
		arg.Comment,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Time,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
